### ISSUE TITLE
For what does WIP stand for?

### ISSUE THREAD

**Issue by Jeeppler** [Tox-Docs/Text#11]
The repository README.md mention WIP, but for what does WIP stand for?

**Comment by Impyy** [comment]
Work in progress?

**Comment by Zer0-One** [comment]
Work In Progress

**Comment by installgen2** [comment]
ayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by GrayHatter** [comment]
@Jeeppler  or @irungentoo close?
