### ISSUE TITLE
Why 32? Why 8? For every number, please add a [...]

### ISSUE THREAD

**Issue by iphydf** [Tox-Docs/Text#32]
https://github.com/Tox-Docs/Text/blob/master/src_text/DHT.txt#L54

Comment on
```
Toxcore stores the 32 nodes
```
found at column 1.

Why 32? Why 8? For every number, please add a reason for it, and a reasonable range for other implementations. Describe the effect a change to those numbers has on the distributed system and on the node itself.

**Comment by irungentoo** [comment]
I picked these numbers because they felt like the best numbers and since they worked they stayed the same.

Not sure how to explain that in the docs.

**Comment by GrayHatter** [comment]
@irungentoo "Unless otherwise specified, each number was chosen because it was likely to be the best, and haven't been changed for legacy compatibility."

**Comment by irungentoo** [comment]
https://github.com/Tox-Docs/Text/commit/b74d74781d8108e3422a51cbc32ca02dda2a49b1
