### ISSUE TITLE
[net_crypto] How many keys does an attacker need to pre-generate to do an effective DoS on a single [...]

### ISSUE THREAD

**Issue by iphydf** [Tox-Docs/Text#44]
https://github.com/Tox-Docs/Text/blob/master/src_text/net_crypto.txt#L14

Comment on
```
simple packet flood
```
found at column 405.

How many keys does an attacker need to pre-generate to do an effective DoS on a single user?

**Comment by irungentoo** [comment]
That would depend on the implementation and the amount of memory the machine has.

**Comment by iphydf** [comment]
Can you make an estimate based on a specified configuration and implementation?

**Comment by irungentoo** [comment]
I could but I don't think it belongs in the docs.
