### ISSUE TITLE
[crypto_core] How are nonces generated?

### ISSUE THREAD

**Issue by iphydf** [Tox-Docs/Text#45]
https://github.com/Tox-Docs/Text/blob/master/src_text/net_crypto.txt#L20

Comment on
```
Random nonce
```
found at column 2.

What random source is this nonce generated from?

**Comment by irungentoo** [comment]
It doesn't matter because nonces don't need to be cryptographically random.

**Comment by iphydf** [comment]
Ok, what is the source of the nonces in the current implementation? Is each nonce completely random, or are they generated in some relation to each other? E.g. monotonically increasing or decreasing, fibonacci, or some other function applied to a number of preceding nonces?

Nonces don't need to be cryptographically random in order to have working crypto, but the source does matter because these numbers are passed around in plain text, so knowing how they are generated may expose an attack vector.

**Comment by irungentoo** [comment]
All nonces for all parts of toxcore are currently generated the same way so I think this info belongs somewhere other than net_crypto.

**Comment by iphydf** [comment]
https://github.com/Tox-Docs/Text/blob/master/src_text/crypto_core.txt
