### ISSUE TITLE
[TCP_server] In what situation does this occur? [...]

### ISSUE THREAD

**Issue by iphydf** [Tox-Docs/Text#51]
https://github.com/Tox-Docs/Text/blob/master/src_text/TCP_server.txt#L11

Comment on
```
send data to friends who may not know that we are connected to the current TCP server while we know they are
```
found at column 650.

In what situation does this occur? Also, can this in theory be used for all communications, and the data packets are an optimisation, or are there limits to what can be sent via OOB (apart from the size limit)? It might make sense to increase that limit so that TCP clients can choose to use the less efficient OOB method to establish a connection once it runs out of connection IDs. It can later, when another connection is closed, establish a real connection and continue there.

**Comment by irungentoo** [comment]
The good behaviour for TCP clients when they run out of connection ids would be to use other relays for new connections, not to use OOB packets. Also due to how it works reaching the limit would be very difficult in normal conditions.
