### ISSUE TITLE
[DHT] The crypto explanation is not sufficiently detailed. [...]

### ISSUE THREAD

**Issue by iphydf** [Tox-Docs/Text#73]
https://github.com/Tox-Docs/Text/blob/master/src_text/DHT.txt#L29

Comment by Barr Detwix on
```
due to how the encryption works
```
found at column 371.

The crypto explanation is not sufficiently detailed.

This could use a short explanation of what the actual crypto used is (symmetric, derives the same key on both ends?) and why it needs protection against replays. On first read I though "Encrypted with the nonce, private DHT key of the sender and public DHT key of the receiver" implied asymetric crypto, which made no sense.

**Comment by irungentoo** [comment]
https://github.com/Tox-Docs/Text/commit/d628d555985efe63fec0db2ca71571ecc91d2732
